newfold-labs/wp-module-solutions

includes/js/debug.json
Since the API response now includes the currency, we can update the debug json data to also include it so the shapes remain in sync.
=> update debug json since response now includes the currency symbol

includes/js/myPluginsTools.js
We had to change the PLS properties in the response since the PLS slug wasn't always matching the plugin slug. We've added a plsSlug value and updated providerName to PlsProviderName. This PR updates the references to the old values to the new ones.
=> Update pls attributes to match updated api response

components/entitlements/EntitlementsCard.js, components/entitlements/Section.js, components/entitlements/index.js, package-lock.json, package.json
My plugins & tools page as per [JIRA](https://jira.newfold.com/browse/PRESS0-1723)
=> PRESS0-1723: WP Admin | Branded Plugin | Solutions Entitlements Page

components/entitlements/EntitlementsCard.js, components/entitlements/index.js, package-lock.json, package.json
Install & activate plugin functionality added to My plugins & tools page.
=> Install & activate plugins data attributes added

components/entitlements/EntitlementsCard.js
adding `data-nfd-installer-plugin-activate` to activate the plugin once the plugin is installed
=> adding data-nfd-installer-plugin-activate to activate the plugin once the plugin is installed

includes/EntitlementsApi.php
=> Fix `set_the_transient` not found

components/entitlements/EntitlementsCard.js, includes/js/myPluginsTools.js
Jira: https://jira.newfold.com/browse/PRESS0-2281
- Reverse the direction
- Make sure that clicking on the arrows will toggle the accordion.
- Added data attributes `data-nfd-installer-plugin-name` and `data-nfd-installer-plugin-url`
https://github.com/user-attachments/assets/f6128595-43db-4b81-939a-3eb68f6e0b1c
=> PRESS0-2281 | Fix arrows on accordion

components/entitlements/EntitlementsCard.js
- Fix for React warnings in console for My plugins & tools page in BH
- Updated data attributes for installation of premium plugins as discussed with @arunshenoy99 
- Removed storageKey
=> React warnings fix for My plugins & tools page in BH

components/entitlements/EntitlementsCard.js, components/entitlements/index.js, includes/Solutions.php, includes/js/myPluginsTools.js
- Add "My Plugins & Tools" on sidebar nav under plugins section
- [PRESS0-2308](https://jira.newfold.com/browse/PRESS0-2308) | If a category has no entitlements, don't render them
- Bluehost entitlements page
- Make items alphabetical
- Padding near buttons
- WP entitlements page
- Make items alphabetical
- Add redirect (use href) for already installed but inactive plugins
- [PRESS0-2309](https://jira.newfold.com/browse/PRESS0-2309) | Issues Observed in 'My plugins and Tools' section
=> Solutions bug fixes

components/entitlements/EntitlementsCard.js, includes/Solutions.php, includes/js/myPluginsTools.js
=> added data attributes

composer.lock, includes/Solutions.php, includes/js/myPluginsTools.js
=> plugin-provider to pls-provider

includes/Solutions.php, includes/js/debug.json
Update the Plugins sub nav item to `My Plugins & Tools` rather than `My plugins & Tools`.
=> capital P dangit

tests/cypress/integration/solutions-app.cy.js, tests/cypress/integration/solutions-plugins.cy.js
The intercept seems to be registered after the request for the entitlements occurs and causing tests to fail sometimes in the release branch of the plugin.
=> move the intercept statement to beginning

components/entitlements/EntitlementsCard.js, components/entitlements/index.js, tests/cypress/integration/solutions-app.cy.js, tests/cypress/integration/solutions-plugins.cy.js, tests/cypress/wp-module-support/utils.cy.js
=> reorder cli commands, add expiration var

components/entitlements/EntitlementsCard.js
https://jira.newfold.com/browse/PRESS0-2430
Added a comment in the story with a better explaination.
=> FIX not Redirecting Bug

components/entitlements/EntitlementsCard.js, components/entitlements/index.js
This PR buttons up some i18n strings:
- add strings to constants object for plugin-based overrides.
- also adds errorMsg var to manage error message.
These component files are loaded into the plugin app, so the strings need to be translatable and also managed in the constants.text object so the plugin can send plugin strings in here too, since they'll need the plugin text-domain.
=> More i18n updates

tests/cypress/fixtures/entitlements-premium.json
Here's a fixture of the new endpoint response. The data is mostly real, but some dummy content for now. Once we get the products all updated in hiive we can update this file, but this should be enough to go on for now.
=> add new entitlements json

includes/EntitlementsApi.php, includes/Solutions.php, tests/cypress/integration/addnew-plugins-installation-check.cy.js, tests/cypress/integration/addnew-plugins-installation-jetpack.cy.js, tests/cypress/integration/addnew-plugins-installation-yoast.cy.js, tests/cypress/integration/addnew-plugins-my-solutions-app.cy.js, tests/cypress/integration/solutions-page-app.cy.js, tests/cypress/wp-module-support/utils.cy.js
Debugging why tests fail in runner but pass locally.
=> Fix tests with fixtures passed in cli command

src/solutions-page/components/tools/upgrade-card/UpgradeCard.js
Fixes empty upsell card button. Adds href and ctb attributes for WP_SOLUTION_FAMILY ctb.
=> Fix upgrade card button

includes/Solutions.php
jira: https://jira.newfold.com/browse/PRESS0-2710
PR adds a custom hidden wp admin URL **`admin.php?page=check-jetpack-connection`** which checks if Jetpack is connected using the Jetpack Connection Manager class. Based on the result, it redirects the user either to the Jetpack Forms responses page (if connected) or the Jetpack onboarding dashboard (if not connected).
=> Checks Jetpack connection status and redirects the user accordingly to Jetpack Forms or dashboard
